### PR TITLE
fix for HTI

### PR DESCRIPTION
**Pull request by artod83**
Changed getSecondaryTeam so that it works with 3 teams or more, added getNumberOfTeams to determine how many there are.

	public function getNumberOfTeams($userId = null)
	{
		$params = array('file'=>'teamdetails', 'version'=>'3.4');
		if($userId !== null)
		{
			$params['userID'] = $userId;
		}
		$url = $this->buildUrl($params);
		$xml = $this->fetchUrl($url);
		if($this->canLog())
		{
			$this->log("URL: ".$url);
		}
	
		$doc = new DOMDocument('1.0', 'UTF-8');
		$doc->loadXml($xml);
	
		$teams = $doc->getElementsByTagName('Team');
		$this->nTeams=$teams->length;
		return $this->nTeams;
	}
		
	/**
	 * Returns HTTeam object with the user's secondary team (or tertiary if $secIndex is specified)
	 *
	 * @param Integer $userId
	 * @param Integer $secIndex
	 * @return HTTeam
	 */
	public function getSecondaryTeam($userId = null, $secIndex=0)
	{
		if(!isset($this->secondaryTeam[$userId]) || $this->secondaryTeam[$userId] === null)
		{
			$params = array('file'=>'teamdetails', 'version'=>'3.4');
			if($userId !== null)
			{
				 $params['userID'] = $userId;
			}
			$url = $this->buildUrl($params);
			$xml = $this->fetchUrl($url);

			$doc = new DOMDocument('1.0', 'UTF-8');
			$doc->loadXml($xml);

			$teams = $doc->getElementsByTagName('Team');
			for($t=0; $t<$teams->length; $t++)
			{
				$txml = new DOMDocument('1.0', 'UTF-8');
				$txml->appendChild($txml->importNode($teams->item($t), true));
				if(strtolower($txml->getElementsByTagName('IsPrimaryClub')->item($t)->nodeValue) == 'true')
				{
					$doc->getElementsByTagName('Teams')->item(0)->removeChild($teams->item($t));
				}
			}
			if($doc->getElementsByTagName('Team')->length)
			{
				$resxml = new DOMDocument('1.0', 'UTF-8');
				$resxml->appendChild($resxml->importNode($teams->item($secIndex), true));
				$this->secondaryTeam[$userId] = new HTTeam($resxml->saveXML());
			}
			else
			{
				return null;
			}
		}
		return $this->secondaryTeam[$userId];
	}

### CODE REVIEW

**Comment by jetwitaussi** [comment]
You mixed branch, if you work on branch v2 you must do a PR on v2 branch.
A branch with conflict can't be merged.
And v2 is incompatible with v3, code can't be merged between both.

However, the way you modify getSecondaryTeam() will give wrong result if users has a hti team without second team (that will happen soon)

I think it's better to just adapt getSecondaryTeam() to check league id
And add a getHTITeam() function that check league id and return correct team

**Comment by artod83** [comment]
Sorry for the mixup. I think that with this code, one should always call getNumberOfTeams first and call getSecondaryTeam with secIndex set to 1 only if getNumberOfTeams = 3. With two teams, primary and HTI, getSecondaryTeam (secIndex=0) should return the HTI team.

**Comment by jetwitaussi** [comment]
The HTI team is quite specific, with specific leagueID and so on.
If when you call getSecondaryTeam() you may have a normal team or a HTI team it could break some code.
I think it's better to add new method and be sure to return null for getSecondaryTeam when there is no normal second team, as this case should already handle by people

Btw, there is still confict in your commit, so it's not possible to merge even if i would be ok :)

**Comment by jetwitaussi** [comment]
and the commit does not contain you code... you should not paste your code in a comment, but in a commit then do a pull request

**Comment by artod83** [comment]
I don't know how to do it. :-D

25. feb. 2017 15:31 je oseba "Telesphore" <notifications@github.com>
napisala:

**Comment by artod83** [comment]
I don't know how to do it. :-D

25. feb. 2017 15:31 je oseba "Telesphore" <notifications@github.com>
napisala:

and the commit does not contain you code... you should not paste your code
in a comment, but in a commit then do a pull request

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jetwitaussi/PHT/pull/9#issuecomment-282487465>, or mute
the thread

**Pull request closed without merging**
