### PR TITLE
fix getRound index

### PR DESCRIPTION
**Pull request by lucaxvi**

### CODE REVIEW

**Review by jetwitaussi — DISMISSED** [review]
In fact to fix it correctly you must do:
id <= 13 + Config\Config::$forIndex
So either you got 0 to 13 or 1 to 14

**Review by jetwitaussi — COMMENTED** [review]
Why <= 14 + forIndex ? you may loop to 15 that would cause error. you have to do >= forIndex to <= 13 + forIndex (as forIndex can be 0 or 1 depending on how you handle loop)

**Comment by lucaxvi** [comment]
.

**Comment by jetwitaussi** [comment]
you have to define STARTING_INDEX at 1 in pht config

this is used as $forIndex, for compatibility with v2 in which all loops started from 1 to number; now in v3 loops are from 0 to number-1, so adjusting the config let you have what you prefer :)

**Comment by lucaxvi** [comment]
nvm

**Comment by jetwitaussi** [comment]
oh :-(

sorry for all my comments, i just want to fix the bug the best way. it's not my intention to skip your MR, you're welcome to contribute!

**Pull request closed without merging**
